# Site settings
title: NaughtyArts
email: bigaaa23@gmail.com
description: "MovieMaking"


# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
encoding: utf-8

port: 3000

sass:
  sass_dir: assets/css
  style: :compressed